[dev]
  port = 8888
  publish = "dist"

[build]
  publish = "dist/"
  command = "npm run build"

# Redirect anything that isn't root to `/api`
[[redirects]]
  from = "/*"
  to = "/api/:splat"

[[edge_functions]]
  path = "/api/*"
  function = "github-get-latest"
